name: kraken_devtools
description: A kraken plugin which open a service to support Chrome DevTools for debugging.
version: 0.4.0
author: Kraken Team
homepage: https://openkraken.com

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^1.1.1
  kraken: ^0.9.0
  meta: ^1.3.0
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
# flutter:
#   plugin:
#     platforms:
#       android:
#         package: com.example.kraken_devtools
#         pluginClass: KrakenDevtoolsPlugin
#       ios:
#         pluginClass: KrakenDevtoolsPlugin
#       macos:
#         pluginClass: KrakenDevtoolsPlugin
